### ISSUE TITLE
Create Calendar

### ISSUE THREAD

**Issue by sepehrRez** [Ishita7078/SoftwareDevProject#13]
Acceptance Criteria:
The calendar feature in WhiteBoard will allow users to assign task deadlines, schedule meetings, and add important events, ensuring that everyone in the group is aware of upcoming commitments. The calendar provides basic functionalities like viewing, adding, and removing tasks, making it easy to stay organized and track project timelines.

**Comment by sepehrRez** [comment]
users should be able to view, add or remove tasks in calendar

**Comment by Prsi1503** [comment]
The calendar feature in WhiteBoard will allow users to efficiently manage and coordinate team schedules. Users can assign task deadlines, schedule meetings, and add important events, ensuring that everyone in the group is aware of upcoming commitments. The calendar provides basic functionalities like viewing, adding, and removing tasks, making it easy to stay organized and track project timelines.
